// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXcGXDhnweUS8roxZeJyzqJMy8YuBCDMQ',
    appId: '1:136492130886:web:cd301e98225fe6d9682047',
    messagingSenderId: '136492130886',
    projectId: 'kofund-153ba',
    authDomain: 'kofund-153ba.firebaseapp.com',
    storageBucket: 'kofund-153ba.firebasestorage.app',
    measurementId: 'G-MK9R46XCV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBgRegrFPDpsYi_-P_mM-fMnzdGywsuJo',
    appId: '1:136492130886:android:19d8e4c483e12fc6682047',
    messagingSenderId: '136492130886',
    projectId: 'kofund-153ba',
    storageBucket: 'kofund-153ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3YexRkt_s1Mt8y1Ce4V_tNN8SYi9R8Jo',
    appId: '1:136492130886:ios:2dd6ad86f94718bd682047',
    messagingSenderId: '136492130886',
    projectId: 'kofund-153ba',
    storageBucket: 'kofund-153ba.firebasestorage.app',
    iosBundleId: 'com.example.kofund',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3YexRkt_s1Mt8y1Ce4V_tNN8SYi9R8Jo',
    appId: '1:136492130886:ios:2dd6ad86f94718bd682047',
    messagingSenderId: '136492130886',
    projectId: 'kofund-153ba',
    storageBucket: 'kofund-153ba.firebasestorage.app',
    iosBundleId: 'com.example.kofund',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXcGXDhnweUS8roxZeJyzqJMy8YuBCDMQ',
    appId: '1:136492130886:web:8ad09dbed6d8b59c682047',
    messagingSenderId: '136492130886',
    projectId: 'kofund-153ba',
    authDomain: 'kofund-153ba.firebaseapp.com',
    storageBucket: 'kofund-153ba.firebasestorage.app',
    measurementId: 'G-CYBSFK4C8D',
  );
}
