// lib/features/history/utils/contribution_receipt_pdf.dart
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import 'package:path_provider/path_provider.dart';
import 'dart:io';

import '../providers/history_provider.dart';

class ContributionReceiptPdf {
  // Generate PDF bytes
  static Future<Uint8List> _generatePdfBytes(
    HistoryItem item, {
    String? communityName,
  }) async {
    final pdf = pw.Document();
    final dtFormat = DateFormat.yMMMMd().add_jm();
    
    // Use a simple "Rs." instead of rupee symbol to avoid font issues
    final amountText = 'Rs. ${NumberFormat('#,##0.00').format(item.amount)}';

    String txId = item.id;
    if (txId.startsWith('contrib_')) txId = txId.replaceFirst('contrib_', '');

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(24),
        build: (pw.Context pwContext) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'KoFund — Contribution Receipt',
                style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 12),
              if (communityName != null && communityName.isNotEmpty)
                pw.Text(
                  'Community: $communityName',
                  style: pw.TextStyle(fontSize: 12),
                ),
              pw.SizedBox(height: 8),
              pw.Divider(),
              pw.SizedBox(height: 8),
              pw.Text(
                'Contributor: ${_extractContributorFromSubtitle(item.subtitle)}',
                style: pw.TextStyle(fontSize: 14),
              ),
              pw.SizedBox(height: 6),
              pw.Text(
                'Program: ${item.title}',
                style: pw.TextStyle(fontSize: 14),
              ),
              pw.SizedBox(height: 6),
              pw.Text(
                'Amount: $amountText',
                style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 6),
              pw.Text(
                'Date & Time: ${dtFormat.format(item.date)}',
                style: pw.TextStyle(fontSize: 12),
              ),
              pw.SizedBox(height: 6),
              pw.Text(
                'Transaction ID: $txId',
                style: pw.TextStyle(fontSize: 12),
              ),
              pw.SizedBox(height: 12),
              pw.Divider(),
              pw.SizedBox(height: 8),
              pw.Text(
                'Thank you for your contribution!',
                style: pw.TextStyle(fontSize: 12),
              ),
              pw.Spacer(),
              pw.Text(
                'Generated by KoFund',
                style: pw.TextStyle(fontSize: 10, color: PdfColors.grey),
              ),
            ],
          );
        },
      ),
    );

    return await pdf.save();
  }

  // Show PDF Preview with Download & Share options
  static Future<void> showPreview(
    BuildContext context,
    HistoryItem item, {
    String? communityName,
  }) async {
    // Show loading dialog
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => const AlertDialog(
        content: Row(
          children: [
            CircularProgressIndicator(),
            SizedBox(width: 16),
            Text('Generating receipt...'),
          ],
        ),
      ),
    );

    try {
      // Generate PDF bytes once and reuse them
      final pdfBytes = await _generatePdfBytes(item, communityName: communityName);
      
      // Close loading dialog
      if (context.mounted) {
        Navigator.of(context).pop();
      }

      // Show preview dialog with the pre-generated bytes
      await showDialog(
        context: context,
        barrierDismissible: true,
        builder: (context) => PdfPreviewDialog(
          pdfBytes: pdfBytes,
          item: item,
          communityName: communityName,
        ),
      );
    } catch (e) {
      if (context.mounted) {
        Navigator.of(context).pop();
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to generate receipt: $e')),
        );
      }
    }
  }

  // ✅ FIXED: Safe method to close only receipt dialogs
  static void _closeReceiptDialogs(BuildContext context) {
    // Only pop once to close the current receipt dialog
    // Don't use popUntil as it navigates back to main screen
    if (Navigator.of(context).canPop()) {
      Navigator.of(context).pop();
    }
  }

  // ✅ FIXED: Download PDF to device - no navigation
  static Future<void> downloadPdf(
    BuildContext context,
    Uint8List pdfBytes,
    HistoryItem item, {
    String? communityName,
  }) async {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => const AlertDialog(
        content: Row(
          children: [
            CircularProgressIndicator(),
            SizedBox(width: 16),
            Text('Saving receipt...'),
          ],
        ),
      ),
    );

    try {
      final directory = await getExternalStorageDirectory();
      final downloadsPath = Directory('/storage/emulated/0/Download');
      
      // Use Downloads folder if available, otherwise use app directory
      final saveDir = await downloadsPath.exists() ? downloadsPath : directory;
      final fileName = 'Kofund_Receipt_${item.id}_${DateTime.now().millisecondsSinceEpoch}.pdf';
      final filePath = '${saveDir?.path}/$fileName';
      final file = File(filePath);
      
      await file.writeAsBytes(pdfBytes);

      if (context.mounted) {
        Navigator.of(context).pop(); // Close saving dialog
        
        // ✅ FIXED: Only close the current receipt dialog, not all dialogs
        // This keeps the user in Contribution History screen
        _closeReceiptDialogs(context);
        
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Receipt downloaded successfully!'),
            duration: Duration(seconds: 2),
          ),
        );
      }
      
      print('Receipt saved to: $filePath');
    } catch (e) {
      if (context.mounted) {
        Navigator.of(context).pop(); // Close saving dialog
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Download failed: $e')),
        );
      }
    }
  }

  // ✅ FIXED: Share PDF - no navigation
  static Future<void> sharePdf(
    BuildContext context,
    Uint8List pdfBytes,
    HistoryItem item, {
    String? communityName,
  }) async {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => const AlertDialog(
        content: Row(
          children: [
            CircularProgressIndicator(),
            SizedBox(width: 16),
            Text('Preparing receipt...'),
          ],
        ),
      ),
    );

    try {
      final tempDir = await getTemporaryDirectory();
      final fileName = 'Kofund_Receipt_${item.id}.pdf';
      final filePath = '${tempDir.path}/$fileName';
      final file = File(filePath);
      
      await file.writeAsBytes(pdfBytes);

      if (context.mounted) {
        Navigator.of(context).pop(); // Close preparing dialog
        
        // ✅ FIXED: Only close the current receipt dialog, not all dialogs
        _closeReceiptDialogs(context);
      }

      await Share.shareXFiles(
        [XFile(filePath, mimeType: 'application/pdf')],
        subject: 'KoFund Receipt - ${item.title}',
        text: 'Receipt for my contribution to ${item.title}',
      );
    } catch (e) {
      if (context.mounted) {
        Navigator.of(context).pop(); // Close preparing dialog
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Share failed: $e')),
        );
      }
    }
  }

  // Legacy method for backward compatibility
  static Future<void> generateAndShare(
    BuildContext context,
    HistoryItem item, {
    String? communityName,
  }) async {
    final pdfBytes = await _generatePdfBytes(item, communityName: communityName);
    String txId = item.id;
    if (txId.startsWith('contrib_')) txId = txId.replaceFirst('contrib_', '');
    await Printing.sharePdf(bytes: pdfBytes, filename: 'kofund_receipt_$txId.pdf');
  }

  static String _extractContributorFromSubtitle(String subtitle) {
    if (subtitle.contains('By:')) {
      final parts = subtitle.split('•')[0].trim();
      return parts.replaceFirst('By:', '').trim();
    }
    return subtitle;
  }
}

// PDF Preview Dialog Widget
class PdfPreviewDialog extends StatefulWidget {
  final Uint8List pdfBytes;
  final HistoryItem item;
  final String? communityName;

  const PdfPreviewDialog({
    Key? key,
    required this.pdfBytes,
    required this.item,
    this.communityName,
  }) : super(key: key);

  @override
  State<PdfPreviewDialog> createState() => _PdfPreviewDialogState();
}

class _PdfPreviewDialogState extends State<PdfPreviewDialog> {
  bool _isDownloading = false;
  bool _isSharing = false;

  void _closeDialog() {
    if (mounted && Navigator.of(context).canPop()) {
      Navigator.of(context).pop();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      insetPadding: const EdgeInsets.all(20),
      child: Container(
        constraints: const BoxConstraints(maxWidth: 600, maxHeight: 800),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            // Header
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: Theme.of(context).primaryColor,
                borderRadius: const BorderRadius.only(
                  topLeft: Radius.circular(12),
                  topRight: Radius.circular(12),
                ),
              ),
              child: Row(
                children: [
                  const Icon(Icons.picture_as_pdf, color: Colors.white),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Text(
                      'Receipt Preview - ${widget.item.title}',
                      style: const TextStyle(
                        color: Colors.white,
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                  IconButton(
                    icon: const Icon(Icons.close, color: Colors.white),
                    onPressed: _closeDialog,
                  ),
                ],
              ),
            ),
            
            // PDF Preview
            Expanded(
              child: PdfPreview(
                build: (format) => widget.pdfBytes,
                allowPrinting: false,
                allowSharing: false,
                canChangePageFormat: false,
                canChangeOrientation: false,
              ),
            ),
            
            // Action Buttons
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                border: Border(top: BorderSide(color: Colors.grey.shade300)),
              ),
              child: Row(
                children: [
                  Expanded(
                    child: OutlinedButton.icon(
                      icon: _isDownloading 
                          ? const SizedBox(
                              width: 16,
                              height: 16,
                              child: CircularProgressIndicator(strokeWidth: 2),
                            )
                          : const Icon(Icons.download),
                      onPressed: _isDownloading || _isSharing
                          ? null
                          : () async {
                              setState(() => _isDownloading = true);
                              try {
                                await ContributionReceiptPdf.downloadPdf(
                                  context,
                                  widget.pdfBytes,
                                  widget.item,
                                  communityName: widget.communityName,
                                );
                                // ✅ FIXED: Don't close dialog automatically after download
                                // Let user decide when to close
                              } catch (e) {
                                if (mounted) {
                                  ScaffoldMessenger.of(context).showSnackBar(
                                    SnackBar(content: Text('Download failed: $e')),
                                  );
                                }
                              } finally {
                                if (mounted) {
                                  setState(() => _isDownloading = false);
                                }
                              }
                            },
                      label: _isDownloading 
                          ? const Text('Downloading...')
                          : const Text('Download'),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: ElevatedButton.icon(
                      icon: _isSharing
                          ? const SizedBox(
                              width: 16,
                              height: 16,
                              child: CircularProgressIndicator(strokeWidth: 2),
                            )
                          : const Icon(Icons.share),
                      onPressed: _isDownloading || _isSharing
                          ? null
                          : () async {
                              setState(() => _isSharing = true);
                              try {
                                await ContributionReceiptPdf.sharePdf(
                                  context,
                                  widget.pdfBytes,
                                  widget.item,
                                  communityName: widget.communityName,
                                );
                                // ✅ FIXED: Don't close dialog automatically after share
                                // Let user decide when to close
                              } catch (e) {
                                if (mounted) {
                                  ScaffoldMessenger.of(context).showSnackBar(
                                    SnackBar(content: Text('Share failed: $e')),
                                  );
                                }
                              } finally {
                                if (mounted) {
                                  setState(() => _isSharing = false);
                                }
                              }
                            },
                      label: _isSharing 
                          ? const Text('Sharing...')
                          : const Text('Share'),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}